"""alteracoes_places

Revision ID: 24640084b19c
Revises: ec8ee485b2bd
Create Date: 2020-09-20 15:53:16.448941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24640084b19c'
down_revision = 'ec8ee485b2bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    nada = None
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    nada = None
    # ### end Alembic commands ###