"""empty message

Revision ID: c48ce91b70ed
Revises: 02b496f0117a
Create Date: 2020-09-20 16:51:29.626635

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c48ce91b70ed'
down_revision = '02b496f0117a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rent', 'checkinDate',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=17),
               existing_nullable=True)
    op.alter_column('rent', 'checkoutDate',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=17),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rent', 'checkoutDate',
               existing_type=sa.String(length=17),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('rent', 'checkinDate',
               existing_type=sa.String(length=17),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###
