"""alteracoes

Revision ID: e2d92519c296
Revises: ec8ee485b2bd
Create Date: 2020-09-20 15:33:06.633473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2d92519c296'
down_revision = 'ec8ee485b2bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checkinDate', sa.String(length=10), nullable=True),
    sa.Column('checkoutDate', sa.String(length=10), nullable=True),
    sa.Column('finalPrice', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rent')
    # ### end Alembic commands ###
